# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 吾爱破解

on:
  workflow_dispatch:
  schedule:
     - cron: '2 9,13 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      PJ_COOKIE: ${{ secrets.PJ_COOKIE }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
          
      - name: '运行 【吾爱破解】'
        if: env.PJ_COOKIE
        run: |
          node Task/52pojie.js
        env:
          YOUTH_READ: ${{ secrets.PJ_COOKIE }}
          